### PR TITLE
Add LCD autoscroll

### PR DESCRIPTION
**Pull request by joppi**

### CODE REVIEW

**Comment by astagi** [comment]
Awesome @joppi! Lcd module is one of the most incomplete parts of Nanpy (drawChar api would be great to  have).. I'll test and merge this  pr in the weekend, no worries for tests failing, I think to remove 2.6 support in the next version or pin a particular version of pyserial ..

**Comment by joppi** [comment]
I intend to use nanpy in a project where I may need the custom char api. I'll look into it then.

**Comment by astagi** [comment]
It would be really great to have the custom char api, @joppi , thanks a lot! :smile:

**Comment by astagi** [comment]
@joppi I've also added the clear method and the official example for autoscroll rewritten in python https://github.com/nanpy/nanpy/blob/4e293daad5af96ee16d93058dda45bae733be9ad/nanpy/examples/lcd_autoscroll.py thanks again! :smile:

**Comment by joppi** [comment]
Well in the end you really did more work on this one ;) thanks

**Comment by astagi** [comment]
@joppi nah I just added an example :smile: can I assign this to you, then? https://github.com/nanpy/nanpy/issues/63

**Comment by joppi** [comment]
@astagi sure, I should have time to look at it this week.

**Comment by astagi** [comment]
sounds great, thank you @joppi ! :smiley:

**Pull request merged**
