### PR TITLE
Added HC-SR04 and TCS34725

### PR DESCRIPTION
**Pull request by omn0mn0m**
Due to a lack of pulseIn, two classes were written for the HC-SR04 (ultrasonic sensor) and TCS34725 (color sensor). PulseIn has been added but does not work as of right now...

Completed:
- Ultrasonic sensor

Un-tested:
- Color sensor

Nonfunctional: 
- PulseIn

### CODE REVIEW

**Comment by ponty** [comment]
Thanks for your contribution.
Please document the hardware you support and how to connect it.
What is your color sensor?
I searched for TCS34725 but this has I2C:
https://www.adafruit.com/product/1334

**Comment by omn0mn0m** [comment]
My bad, I meant the [TCS3200](http://www.robotshop.com/en/tcs3200-color-sensor.html?gclid=Cj0KEQjw5sHHBRDg5IK6k938j_IBEiQARZBJWkxiN_wU371fie8EnsVsmd5-q6ay49I-Xu4GrVTrW3waAkgX8P8HAQ).

**Comment by ponty** [comment]
I checked the spec. You should use S0 = L, S1 = H because pulseIn is for maximum 50kHz (https://www.arduino.cc/en/Reference/pulseIn)

I think that the color sensor can be already implemented in python only using the frequency counter class.

**Comment by omn0mn0m** [comment]
Ah okay then, we were having trouble with it for some reason so that's why we made that.

**Pull request merged**
