### PR TITLE
Add reStructuredText README

### PR DESCRIPTION
**Pull request by Pi3R1k**
reStructuredText README for pypi

### CODE REVIEW

**Comment by astagi** [comment]
wow thanks a lot!! :)

**Comment by ponty** [comment]
1. Badges should be added
2. README.md should be removed

**Comment by astagi** [comment]
@Pi3R1k can you provide badges please? :) 

@ponty looks like license badge remains unknown, why?

**Comment by ponty** [comment]
The  license was not set in the last PYPI release.
It will be OK after the next release. (458d7bf190629e02d14c20c679d687f9befbf2ba)

**Comment by astagi** [comment]
@ponty fixed and added flat style ;)

**Pull request merged**
