### PR TITLE
[NOT TESTED] Permit the use of 4-pin stepper motors.

### PR DESCRIPTION
**Pull request by Krastanov**
https://www.arduino.cc/en/Reference/StepperConstructor - the constructor permits two types of stepper motors (only one of them is supported in nanpy, but 4-pin motors are very common).

I do not know how the code works and I am just guessing. I will test it in a day when I have access to the stepper motor.

The order of the arguments is awkward for backward-compatibility purposes.

### CODE REVIEW

**Comment by astagi** [comment]
Thanks! Please, consider to update the firmware part as well https://github.com/nanpy/nanpy-firmware/blob/master/Nanpy/StepperClass.cpp

And please test your code before :smile: waiting for updates from you...

**Comment by Krastanov** [comment]
I tested it earlier today and it works with the updated firmware (not provided in this pull request). However, how can I write firmware that would work with both 2 pins and 4 pins? Do I need to define 2 different c++ classes?

**Comment by astagi** [comment]
No, Nanpy firmware doesn't support 4 pins at the moment. You need to call a different constructor here, depending on how many parameters you pass to the function:

https://github.com/nanpy/nanpy-firmware/blob/master/Nanpy/StepperClass.cpp#L18

Use m->getNArgs() to see how many parameters are you passing. If the number of paramters is 5 then you're using 4 pins, else you're using 2 pins. Something like this:

```
        if (strcmp(m->getName(),"new") == 0) {       
            int prm = 0;
            if (m->getNArgs() == 5) {
                v.insert(new Stepper (m->getInt(prm++), m->getInt(prm++), m->getInt(prm++)));
           } else {
                v.insert(new Stepper (m->getInt(prm++), m->getInt(prm++), m->getInt(prm++), m->getInt(prm++), m->getInt(prm++)));
           } 
            m->returns(v.getLastIndex());
        }
```

Take a look at the firmware and open a PR with the changes required.

**Comment by Krastanov** [comment]
Noted. I will update both over the weekend.

**Comment by astagi** [comment]
Many thanks @Krastanov ! Feel free to ask me any kind of help you need in the implementation and thanks for contributing to Nanpy! :smile:

**Comment by Krastanov** [comment]
Pull requests https://github.com/nanpy/nanpy-firmware/pull/21 and https://github.com/nanpy/nanpy/pull/65 cover everything from here, so I am closing this PR. Thanks for the detailed explanations.

**Pull request closed without merging**
